//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.7.0
//     from Assets/ControlSchema.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

public partial class @ControlSchema: IInputActionCollection2, IDisposable
{
    public InputActionAsset asset { get; }
    public @ControlSchema()
    {
        asset = InputActionAsset.FromJson(@"{
    ""name"": ""ControlSchema"",
    ""maps"": [
        {
            ""name"": ""Jumper"",
            ""id"": ""669f8bad-f0b0-4fd2-876f-d746eca16003"",
            ""actions"": [
                {
                    ""name"": ""Jump"",
                    ""type"": ""Button"",
                    ""id"": ""60c3ae05-c719-4dbd-acdc-84b2224a8398"",
                    ""expectedControlType"": ""Button"",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""201bc5a5-4527-4eb9-8148-07c46ae353d4"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Jump"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Jumper
        m_Jumper = asset.FindActionMap("Jumper", throwIfNotFound: true);
        m_Jumper_Jump = m_Jumper.FindAction("Jump", throwIfNotFound: true);
    }

    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    public void Enable()
    {
        asset.Enable();
    }

    public void Disable()
    {
        asset.Disable();
    }

    public IEnumerable<InputBinding> bindings => asset.bindings;

    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Jumper
    private readonly InputActionMap m_Jumper;
    private List<IJumperActions> m_JumperActionsCallbackInterfaces = new List<IJumperActions>();
    private readonly InputAction m_Jumper_Jump;
    public struct JumperActions
    {
        private @ControlSchema m_Wrapper;
        public JumperActions(@ControlSchema wrapper) { m_Wrapper = wrapper; }
        public InputAction @Jump => m_Wrapper.m_Jumper_Jump;
        public InputActionMap Get() { return m_Wrapper.m_Jumper; }
        public void Enable() { Get().Enable(); }
        public void Disable() { Get().Disable(); }
        public bool enabled => Get().enabled;
        public static implicit operator InputActionMap(JumperActions set) { return set.Get(); }
        public void AddCallbacks(IJumperActions instance)
        {
            if (instance == null || m_Wrapper.m_JumperActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_JumperActionsCallbackInterfaces.Add(instance);
            @Jump.started += instance.OnJump;
            @Jump.performed += instance.OnJump;
            @Jump.canceled += instance.OnJump;
        }

        private void UnregisterCallbacks(IJumperActions instance)
        {
            @Jump.started -= instance.OnJump;
            @Jump.performed -= instance.OnJump;
            @Jump.canceled -= instance.OnJump;
        }

        public void RemoveCallbacks(IJumperActions instance)
        {
            if (m_Wrapper.m_JumperActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        public void SetCallbacks(IJumperActions instance)
        {
            foreach (var item in m_Wrapper.m_JumperActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_JumperActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    public JumperActions @Jumper => new JumperActions(this);
    public interface IJumperActions
    {
        void OnJump(InputAction.CallbackContext context);
    }
}
